name: Daily Commit

on:
  schedule:
    - cron: "40 16 * * *"
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes and commit
        run: |
          echo "$(date)" > last_run.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "24f1001631@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit - $(date)"
          git push
